### ISSUE TITLE
Angular Universal Error

### ISSUE THREAD

**Issue by caztial** [BioPhoton/angular-star-rating#46]
node_modules/angular-star-rating/index.js:1
(function (exports, require, module, __filename, __dirname) { import { Component, EventEmitter, NgModule, forwardRef } from '@angular/core';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/~/~/~/src/app/app.module.ts:28:1)

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

**Comment by caztial** [comment]
it's regarding the build. try to make it compatible with node as well.

**Comment by khalid-halo** [comment]
@caztial , ANy workarounds for the time being?

**Comment by sagarguhe** [comment]
@caztial Any work arround?

**Comment by BioPhoton** [comment]
@caztial Could you try the latest version (4.0.0-beta.1) i updated the packaging code.
